#!/bin/bash

#Oracle Cloud Infrastrure Dataflow
#
#Copyright © 2025, Oracle and/or its affiliates.
#
#Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/


set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Spark History Server — Entrypoint
#
# 1. Rewrites host-absolute paths in ~/.oci/config → container paths
# 2. Writes spark-defaults.conf from env vars
# 3. Starts the OCI log preparer (background watch or one-shot)
# 4. Starts the Spark History Server in the foreground
# ─────────────────────────────────────────────────────────────

log()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] ENTRYPOINT  $*"; }
warn() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] ENTRYPOINT  WARN $*"; }
err()  { echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR       $*" >&2; }

SPARK_HOME="${SPARK_HOME:-/opt/spark}"
CONF_DIR="$SPARK_HOME/conf"
OUTPUT_DIR="${OUTPUT_DIR:-/shs-logs}"
SHS_PORT="${SHS_PORT:-18080}"
WATCH_MODE="${WATCH_MODE:-true}"
POLL_INTERVAL="${POLL_INTERVAL:-300}"
OCI_CONFIG_FILE="${OCI_CONFIG_FILE:-/root/.oci/config}"
OCI_CONFIG_DIR="$(dirname "$OCI_CONFIG_FILE")"

mkdir -p "$OUTPUT_DIR"
# Ensure the output directory has proper permissions for Spark to read
chmod -R 755 "$OUTPUT_DIR"
chown -R root:root "$OUTPUT_DIR"
# Also ensure directory itself is readable/executable
ls -laR "$OUTPUT_DIR"
# Recursively fix all permissions
chmod -R 755 "$OUTPUT_DIR"

# ── 1. Rewrite host paths in OCI config ──────────────────────
# The OCI CLI config on the host contains absolute host paths like:
#   key_file=/Users/alice/.oci/sessions/PROFILE/oci_api_key.pem
#   security_token_file=/Users/alice/.oci/sessions/PROFILE/token
#
# Inside the container the ~/.oci directory is mounted at
# $OCI_CONFIG_DIR (/root/.oci by default). We rewrite every
# path that points outside the container to the equivalent
# container-local path by replacing the host prefix with
# $OCI_CONFIG_DIR.
patch_oci_config() {
  if [[ ! -f "$OCI_CONFIG_FILE" ]]; then
    warn "OCI config not found at $OCI_CONFIG_FILE — skipping path rewrite"
    return
  fi

  # Work on a writable copy so we never modify the host-mounted original
  local patched="/tmp/oci_config_patched"
  cp "$OCI_CONFIG_FILE" "$patched"

  # Detect the host-side ~/.oci prefix by scanning for the first
  # key_file or security_token_file entry that looks like an absolute
  # path pointing outside the container.
  # NOTE: Use '=?' to match both "key_file=value" and "key_file = value"
  local host_oci_prefix
  host_oci_prefix=$(grep -E '^\s*(key_file|security_token_file)=?' "$patched" \
    | grep -v "^$OCI_CONFIG_DIR" \
    | head -1 \
    | sed -E 's|.*=?||; s|/sessions/.*||; s|/[^/]*\.pem||' \
    | xargs \
    || true)

  if [[ -z "$host_oci_prefix" ]]; then
    log "OCI config paths already use container paths — no rewrite needed"
    # Still use the copy so prepare_logs.sh points at /tmp version
    export OCI_CONFIG_FILE="$patched"
    return
  fi

  log "Rewriting OCI config paths:"
  log "  host prefix   : $host_oci_prefix"
  log "  container dir : $OCI_CONFIG_DIR"

  # Replace every occurrence of the host prefix with the container dir
  sed -i "s|${host_oci_prefix}|${OCI_CONFIG_DIR}|g" "$patched"

  # Show what changed
  log "Patched key/token file entries:"
  grep -E '^\s*(key_file|security_token_file)=?' "$patched" \
    | sed 's/^/  /' || true

  # Validate that all referenced files now actually exist
  local missing=0
  while IFS= read -r filepath; do
    if [[ ! -f "$filepath" ]]; then
      err "  MISSING: $filepath"
      missing=$(( missing + 1 ))
    else
      log "  OK: $filepath"
    fi
  done < <(grep -E '^\s*(key_file|security_token_file)=?' "$patched" \
             | sed -E 's|.*=?||' | xargs -I{} echo {})

  if [[ $missing -gt 0 ]]; then
    err "$missing referenced file(s) not found in the container."
    err "Make sure you mount the full ~/.oci directory, not just the config file:"
    err "  -v ~/.oci:/root/.oci:ro"
    exit 1
  fi

  export OCI_CONFIG_FILE="$patched"
  log "OCI config ready at $OCI_CONFIG_FILE"
}

# ── 2. Write runtime-resolved spark-defaults.conf ────────────
write_spark_conf() {
  log "Writing spark-defaults.conf → $CONF_DIR/spark-defaults.conf"
  mkdir -p "$CONF_DIR"

  cat > "$CONF_DIR/spark-defaults.conf" << SPARKCONF
# Auto-generated by entrypoint at $(date -u '+%Y-%m-%dT%H:%M:%SZ')

spark.history.fs.logDirectory               file://${OUTPUT_DIR}
spark.history.ui.port                       ${SHS_PORT}
spark.history.ui.maxApplications            ${SHS_MAX_APPLICATIONS:-500}
spark.history.retainedApplications          ${SHS_RETAINED_APPLICATIONS:-100}
spark.history.fs.update.interval            ${SHS_UPDATE_INTERVAL:-10s}
spark.history.fs.cleaner.enabled            ${SHS_CLEANER_ENABLED:-false}
spark.io.compression.codec                  none
spark.eventLog.enabled                      true
spark.eventLog.compress                     false
spark.history.ui.acls.enable                ${SHS_ACLS_ENABLED:-false}
SPARKCONF

  log "spark-defaults.conf written:"
  cat "$CONF_DIR/spark-defaults.conf"
}

# ── 3. Start the log preparer ─────────────────────────────────
start_preparer() {
  if [[ "$WATCH_MODE" == "true" ]]; then
    log "Starting log preparer in background watch mode (poll every ${POLL_INTERVAL}s)"
    OCI_CONFIG_FILE="$OCI_CONFIG_FILE" \
    WATCH_MODE=true \
    POLL_INTERVAL="$POLL_INTERVAL" \
    OUTPUT_DIR="$OUTPUT_DIR" \
      /usr/local/bin/prepare_logs.sh &
    log "Log preparer PID: $!"
    log "Waiting 15s for initial log preparation..."
    sleep 15
  else
    log "Running log preparer once (one-shot mode)..."
    OCI_CONFIG_FILE="$OCI_CONFIG_FILE" \
    WATCH_MODE=false \
    OUTPUT_DIR="$OUTPUT_DIR" \
      /usr/local/bin/prepare_logs.sh
    log "One-shot preparation complete."
  fi
}

# ── Main ──────────────────────────────────────────────────────
patch_oci_config
write_spark_conf
start_preparer

log "═══════════════════════════════════════════════"
log " Starting Spark History Server"
log " Log dir : $OUTPUT_DIR"
log " UI      : http://0.0.0.0:${SHS_PORT}"
log "═══════════════════════════════════════════════"

exec "$SPARK_HOME/bin/spark-class" \
  org.apache.spark.deploy.history.HistoryServer
